18 create account modal
harring/hair-salon pull request #22
Opened 2022-12-22 23:00 UTC by Toerngren

Add user model and user controller.

Controller has CRUD (Post, Get by ID, Get All, Put by ID and Delete by ID).

Postman test runs with global variables.

Fix #18
Fix #19

2022-12-22 23:36 UTC, harring requested changes
Clean code and very nice error messages but there are a few things you should look at. 

Hashing and salting password should be done but might be easier to do later(its also not in the issue to do it).

2022-12-22 23:36 UTC, harring commented on backend/controllers/users.js
> +    User.findOne({ _id: req.params.id })
You can use `findById` instead of `findOne` which I believe does the same by comparing _id with req.params.id. It just makes sure it looks at the correct id. You do it on row 32.

2022-12-22 23:36 UTC, harring commented on backend/controllers/users.js
> +    User.findById(id, function(err, user) {
It is possible to use `findByIdAndUpdate` , you can then pass it `req.body` as an argument what to update. This way you dont have to specify what goes where(row 40-42).

2022-12-22 23:36 UTC, harring commented on backend/controllers/users.js
> +    User.findOneAndDelete({_id: id}, function(err, user) {
Similar here, there is `findByIdAndDelete` so that you do not have to compare _id to id.

2022-12-26 18:37 UTC, Toerngren commented on backend/controllers/users.js
> +    User.findOne({ _id: req.params.id })
I changed to findById instead.

2022-12-26 18:52 UTC, Toerngren commented on backend/controllers/users.js
> +    User.findById(id, function(err, user) {
Ok- changed in new push

2022-12-26 18:52 UTC, Toerngren commented on backend/controllers/users.js
> +    User.findOneAndDelete({_id: id}, function(err, user) {
OK

2022-12-26 18:57 UTC, Toerngren commented
@harring Updated code acc. to your suggestions. 
✅ All updated pass Postman tests.  
Added findByID on all places, also added some minor changes to err. messages too. 

Merry Christmas! 🎅🏻

2022-12-29 16:03 UTC, harring approved these changes
Looks good

2022-12-29 16:04 UTC, merged